---
title: "Harmonize normalize drug data"
author: "Sara Gosline"
date: "2025-09-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(synapser)
library(ggplot2)
library(dplyr)
library(tidyr)
```


## Download drug stats
First we need to downlod the summary stats for each organoid .

```{r download, warning=FALSE}
synLogin()

fits<-readr::read_tsv(synGet('syn69947322')$path)

##adding in patient cohort 2

meta1 <- readxl::read_xlsx(syn$get('syn65595365')$path) |>
  tidyr::separate(Specimen,into=c('Patient','Tumor'),sep='_',remove = FALSE)|>
  dplyr::select(Specimen,Patient,Tumor,aliquot)|>
  mutate(cohort=1)

meta2 <- readxl::read_xlsx(syn$get('syn69920464')$path,sheet='Sheet2')|>
  tidyr::separate(Specimen,into=c('Patient','Tumor'),sep='_',remove = FALSE)|>
  dplyr::select(Specimen,Patient,Tumor,aliquot='SampleAlias')|>
  mutate(cohort=2)

meta <- rbind(meta1,meta2)
  


pcols <- c(NF0017='steelblue',NF0021='orange3',NF0019='orchid4',
           NF0022='goldenrod',NF0018='olivedrab',NF0020='darkred', NF0022='tan',
           NF0023='darkgrey',NF0025='lightblue',NF0026='lightyellow',NF0027='magenta3',
           NF0028='lightgreen',NF0031='pink')

```

## Plot data from drug

Here we can write a function that plots data for a drug across patients

```{r summary, echo=FALSE}

 fits|>subset(dose_response_metric=='uM_viability')|>ggplot(aes(x=dose_response_value,y=improve_sample_id,fill=improve_sample_id,alpha=0.5))+ggridges::geom_density_ridges()+ggtitle('Viabilities across samples')

##we can also plot samples according to their drug response
pcs = fits|>subset(dose_response_metric=='uM_viability')|>
  dplyr::select(improve_sample_id,improve_drug_id,dose_response_value)|>
  distinct()|>
  tidyr::pivot_wider(names_from='improve_drug_id',values_from='dose_response_value',values_fill=1.0,values_fn=mean)|>
  tibble::column_to_rownames('improve_sample_id')|>prcomp()

pcs$x|>as.data.frame()|>tibble::rownames_to_column('Specimen')|>
  left_join(meta)|>
  dplyr::select(PC1,PC2,Patient,Specimen)|>
  distinct()|>
  ggplot(aes(x=PC1,y=PC2,col=Patient,label=Specimen))+geom_point()+
  ggrepel::geom_label_repel()+
  ggplot2::scale_color_manual(values=pcols)

```
