---
title: "run_analyze_modality_and_enrichment"
author: "JJ"
date: "2025-11-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


source("00_cNF_helper_code.R")
source("02_analyze_modality_correlations.R")
```

# Load in Data
```{r}

#Drugs
drugs <- readr::read_tsv(synGet("syn69947322")$path)

#RNA 
rlong <- readr::read_csv(synGet('syn71333780')$path)

#Global
glong <- readr::read_csv(synGet('syn70078416')$path)

#Phospho
plong <- readr::read_csv(synGet('syn70078415')$path)

```


# RNA
```{r}
corr_rna <- analyze_modality(
  fits        = drugs,            
  df_long     = rlong,           
  sample_col  = "Specimen",
  feature_col = "feature_id",
  value_col   = "correctedAbundance",
  metric      = "uM_viability",
  heatmap_filename = "rna_drug_heatmap_large_viability.pdf",
  outdir = "new_figs"
)

```


# Global Proteomics
```{r}
corr_global <- analyze_modality(
  fits        = drugs,            
  df_long     = glong,           
  sample_col  = "Specimen",
  feature_col = "Gene",
  value_col   = "correctedAbundance",
  metric      = "uM_viability",
  heatmap_filename = "global_drug_heatmap_large_viability.pdf",
  outdir = "new_figs"
)
```


# Phospho Proteomics
```{r}
corr_phospho <- analyze_modality(
  fits        = drugs,          
  df_long     = plong,           
  sample_col  = "Specimen",
  feature_col = "site",
  value_col   = "correctedAbundance",
  metric      = "uM_viability",
  heatmap_filename = "phospho_drug_heatmap_large_viability.pdf",
  outdir = "new_figs"
)

```
